/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppCatalogoRouteImport } from './routes/_app.catalogo'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppEquipeRouteImport } from './routes/_app.equipe'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppPainelRouteImport } from './routes/_app.painel'
import { Route as AppPedidosRouteImport } from './routes/_app.pedidos'
import { Route as AppProducaoRouteImport } from './routes/_app.producao'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPedidosIndexRouteImport } from './routes/_app.pedidos.index'
import { Route as AppPedidosNovoRouteImport } from './routes/_app.pedidos.novo'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCepCepRouteImport } from './routes/api/cep.$cep'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCatalogoRoute = AppCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosIndexRoute = AppPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPedidosRoute,
} as any)
const AppPedidosNovoRoute = AppPedidosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppPedidosRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCepCepRoute = ApiCepCepRouteImport.update({
  id: '/api/cep/$cep',
  path: '/api/cep/$cep',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catalogo': typeof AppCatalogoRoute
  '/clientes': typeof AppClientesRoute
  '/equipe': typeof AppEquipeRoute
  '/estoque': typeof AppEstoqueRoute
  '/painel': typeof AppPainelRoute
  '/pedidos': typeof AppPedidosRouteWithChildren
  '/producao': typeof AppProducaoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/pedidos/novo': typeof AppPedidosNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cep/$cep': typeof ApiCepCepRoute
  '/pedidos/': typeof AppPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catalogo': typeof AppCatalogoRoute
  '/clientes': typeof AppClientesRoute
  '/equipe': typeof AppEquipeRoute
  '/estoque': typeof AppEstoqueRoute
  '/painel': typeof AppPainelRoute
  '/producao': typeof AppProducaoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/pedidos/novo': typeof AppPedidosNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cep/$cep': typeof ApiCepCepRoute
  '/pedidos': typeof AppPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/catalogo': typeof AppCatalogoRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/painel': typeof AppPainelRoute
  '/_app/pedidos': typeof AppPedidosRouteWithChildren
  '/_app/producao': typeof AppProducaoRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/pedidos/novo': typeof AppPedidosNovoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cep/$cep': typeof ApiCepCepRoute
  '/_app/pedidos/': typeof AppPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalogo'
    | '/clientes'
    | '/equipe'
    | '/estoque'
    | '/painel'
    | '/pedidos'
    | '/producao'
    | '/relatorios'
    | '/pedidos/novo'
    | '/api/auth/$'
    | '/api/cep/$cep'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/catalogo'
    | '/clientes'
    | '/equipe'
    | '/estoque'
    | '/painel'
    | '/producao'
    | '/relatorios'
    | '/pedidos/novo'
    | '/api/auth/$'
    | '/api/cep/$cep'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/catalogo'
    | '/_app/clientes'
    | '/_app/equipe'
    | '/_app/estoque'
    | '/_app/painel'
    | '/_app/pedidos'
    | '/_app/producao'
    | '/_app/relatorios'
    | '/_app/pedidos/novo'
    | '/api/auth/$'
    | '/api/cep/$cep'
    | '/_app/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCepCepRoute: typeof ApiCepCepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/catalogo': {
      id: '/_app/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AppCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao': {
      id: '/_app/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos/': {
      id: '/_app/pedidos/'
      path: '/'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AppPedidosIndexRouteImport
      parentRoute: typeof AppPedidosRoute
    }
    '/_app/pedidos/novo': {
      id: '/_app/pedidos/novo'
      path: '/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AppPedidosNovoRouteImport
      parentRoute: typeof AppPedidosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cep/$cep': {
      id: '/api/cep/$cep'
      path: '/api/cep/$cep'
      fullPath: '/api/cep/$cep'
      preLoaderRoute: typeof ApiCepCepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppPedidosRouteChildren {
  AppPedidosNovoRoute: typeof AppPedidosNovoRoute
  AppPedidosIndexRoute: typeof AppPedidosIndexRoute
}

const AppPedidosRouteChildren: AppPedidosRouteChildren = {
  AppPedidosNovoRoute: AppPedidosNovoRoute,
  AppPedidosIndexRoute: AppPedidosIndexRoute,
}

const AppPedidosRouteWithChildren = AppPedidosRoute._addFileChildren(
  AppPedidosRouteChildren,
)

interface AppRouteChildren {
  AppCatalogoRoute: typeof AppCatalogoRoute
  AppClientesRoute: typeof AppClientesRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppPainelRoute: typeof AppPainelRoute
  AppPedidosRoute: typeof AppPedidosRouteWithChildren
  AppProducaoRoute: typeof AppProducaoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogoRoute: AppCatalogoRoute,
  AppClientesRoute: AppClientesRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppPainelRoute: AppPainelRoute,
  AppPedidosRoute: AppPedidosRouteWithChildren,
  AppProducaoRoute: AppProducaoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCepCepRoute: ApiCepCepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
